/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frontend;

import Data.clsQuerys;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.TimeZone;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SpinnerDateModel;
import javax.swing.SpinnerModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author caarlb
 */
public class frmReporteria extends javax.swing.JFrame {

    /**
     * Creates new form frmReporteria
     */
    public frmReporteria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnReporteProductos = new javax.swing.JButton();
        btnReporteProductos1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        spFechaInicial = new javax.swing.JSpinner();
        spFechaFinal = new javax.swing.JSpinner();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setText("Reporteria");

        btnReporteProductos.setText("Generar Reporte Inventario de Productos");
        btnReporteProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteProductosActionPerformed(evt);
            }
        });

        btnReporteProductos1.setText("Generar Reporte de facturas");
        btnReporteProductos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteProductos1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Desde");

        jLabel3.setText("Hasta");

        jLabel4.setText("D/M/A  H:S");

        spFechaInicial.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(1609531380000L), null, null, java.util.Calendar.DAY_OF_MONTH));

        spFechaFinal.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(1672509540000L), null, null, java.util.Calendar.DAY_OF_MONTH));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReporteProductos)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(spFechaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spFechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addComponent(btnReporteProductos1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel4)))
                .addGap(32, 32, 32))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(btnReporteProductos)
                .addGap(21, 21, 21)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(spFechaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnReporteProductos1)
                        .addGap(8, 8, 8)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(spFechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReporteProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteProductosActionPerformed
        String ruta = obtenerRuta();
        String nombreArchivo = "ReporteProductos";
        String contenido = generarContenidoArchivoProductos();
        if (crearArchivo(ruta, contenido, nombreArchivo)) {
            JOptionPane.showMessageDialog(null, "archivo creado exitosamente", "AVISO", JOptionPane.OK_OPTION);
        } else {
            JOptionPane.showMessageDialog(null, "no se creo el archivo", "AVISO", JOptionPane.OK_OPTION);
        }


    }//GEN-LAST:event_btnReporteProductosActionPerformed

    private void btnReporteProductos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteProductos1ActionPerformed

        Date fInicial = (Date) spFechaInicial.getValue();
        Date fFinal = (Date) spFechaFinal.getValue();
        if (fInicial.before(fFinal)) {

            String ruta = obtenerRuta();
            String nombreArchivo = "ReporteFacturas";
            String contenido = generarContenidoArchivoFactura();
            if (crearArchivo(ruta, contenido, nombreArchivo)) {
                JOptionPane.showMessageDialog(null, "archivo creado exitosamente", "AVISO", JOptionPane.OK_OPTION);
            } else {
                JOptionPane.showMessageDialog(null, "no se creo el archivo", "AVISO", JOptionPane.OK_OPTION);
            }

        } else {
            JOptionPane.showMessageDialog(null, "La fecha inicial debe ser anterior a la fecha final", "AVISO", JOptionPane.OK_OPTION);

        }


    }//GEN-LAST:event_btnReporteProductos1ActionPerformed

    private String generarContenidoArchivoFactura() {

        String fechaInicial, fechaFinal;

        //obtener valores de spinners
        fechaInicial = "" + spFechaInicial.getValue();
        fechaFinal = "" + spFechaFinal.getValue();

        //usando substring para remover el ia el tipo de horario
        fechaInicial = fechaInicial.substring(4, 19) + fechaInicial.substring(23, 28);
        fechaFinal = fechaFinal.substring(4, 19) + fechaFinal.substring(23, 28);
//        System.out.println("fecha inicio: " + fechaInicial);
//        System.out.println("fecha final: " + fechaFinal);

        clsQuerys objFacturas = new clsQuerys();
        DefaultTableModel modeloConDatos;
        modeloConDatos = objFacturas.fncShowReporteFactura(fechaInicial, fechaFinal);

        String rangosDeBusqueda = "Busqueda desde: " + fechaInicial + " hasta " + fechaFinal + "\n";
        String titulos = ""
                + modeloConDatos.getColumnName(0) + " - "
                + modeloConDatos.getColumnName(1) + " - "
                + modeloConDatos.getColumnName(2) + " - "
                + modeloConDatos.getColumnName(3) + "\n";

        int totalFilas = modeloConDatos.getRowCount();
        String valores = "";

        for (int i = 0; i < totalFilas; i++) {
            valores += modeloConDatos.getValueAt(i, 0) + " - ";
            valores += modeloConDatos.getValueAt(i, 1) + " - ";
            valores += modeloConDatos.getValueAt(i, 2) + " - ";
            valores += modeloConDatos.getValueAt(i, 3) + "\n";
        }

        return rangosDeBusqueda + titulos + valores;

    }

    private String generarContenidoArchivoProductos() {

        clsQuerys objProductos = new clsQuerys();
        DefaultTableModel modeloConDatos;
        modeloConDatos = objProductos.fcnShowProductsList();
        String titulos = ""
                + modeloConDatos.getColumnName(0) + " - "
                + modeloConDatos.getColumnName(1) + " - "
                + modeloConDatos.getColumnName(4) + " - "
                + modeloConDatos.getColumnName(5) + " - "
                + modeloConDatos.getColumnName(6) + "\n";

        int totalFilas = modeloConDatos.getRowCount();
        String valores = "";

        for (int i = 0; i < totalFilas; i++) {
            valores += modeloConDatos.getValueAt(i, 0) + " - ";
            valores += modeloConDatos.getValueAt(i, 1) + " - ";
            valores += modeloConDatos.getValueAt(i, 4) + " - ";
            valores += modeloConDatos.getValueAt(i, 5) + " - ";
            valores += modeloConDatos.getValueAt(i, 6) + "\n";
        }

        return "" + titulos + valores;
    }

    private String obtenerRuta() {
        try {
            JFileChooser fc = new JFileChooser();
            fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            int seleccion = fc.showOpenDialog(null);
            if (seleccion == JFileChooser.APPROVE_OPTION) {
                File fichero = fc.getSelectedFile();
                return fichero.getAbsolutePath();
            }
        } catch (Exception e) {
        }
        return "";
    }

    private boolean crearArchivo(String ruta, String contenido, String fileName) {
        try {
            FileWriter f = new FileWriter(ruta + "\\" + fileName + ".txt");
            f.write(contenido);
            f.close();
            return true;
        } catch (IOException e) {
            System.out.println("Hubo un erro al crear el txt " + e);
        }
        return false;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmReporteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmReporteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmReporteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmReporteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new frmReporteria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReporteProductos;
    private javax.swing.JButton btnReporteProductos1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner spFechaFinal;
    private javax.swing.JSpinner spFechaInicial;
    // End of variables declaration//GEN-END:variables
}
