/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frontend;

import Data.clsQuerys;
import java.util.Arrays;
import javax.security.auth.callback.ConfirmationCallback;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author caarlb
 */
public class frmVenta extends javax.swing.JFrame {

    private String[] titulosColumnas;

    private DefaultTableModel modeloConDatosDeTabla;

    /**
     * Creates new form frmVenta
     */
    public frmVenta() {
        this.titulosColumnas = new String[]{"Correlativo", "Codigo", "Nombre", "Cantidad", "Precio", "Subtotal", "No. de Existencias"};
        this.modeloConDatosDeTabla = new DefaultTableModel(null, titulosColumnas);
        initComponents();
    }

    public frmVenta(String nit, String nombre, String direccion) {
        this.titulosColumnas = new String[]{"Correlativo", "Codigo", "Nombre", "Cantidad", "Precio", "Subtotal", "No. de Existencias"};
        this.modeloConDatosDeTabla = new DefaultTableModel(null, titulosColumnas);
        initComponents();
        this.lbNIT.setText(nit);
        this.lbNombreCliente.setText(nombre);
        this.lbDireccion.setText(direccion);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ctBuscarNIT = new javax.swing.JTextField();
        btnBuscarNIT = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        lbNIT = new javax.swing.JLabel();
        lbNombreCliente = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbDireccion = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        ctBuscarProducto = new javax.swing.JTextField();
        cbOpcionDeBusqueda = new javax.swing.JComboBox<>();
        btnBuscarProducto = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lbCodigoProducto = new javax.swing.JLabel();
        lbNombreProducto = new javax.swing.JLabel();
        lbTipoProducto = new javax.swing.JLabel();
        lbFarmaceutica = new javax.swing.JLabel();
        lbPresentacion = new javax.swing.JLabel();
        lbStock = new javax.swing.JLabel();
        lbPrecio = new javax.swing.JLabel();
        lbComposicion = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        spCantidadParaAgregar = new javax.swing.JSpinner();
        btnAgregar = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        lbFactura = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbProductos = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lbTotal = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        lbCantidadProductos = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        cbEstatus = new javax.swing.JComboBox<>();
        btnFacturar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("registro de venta");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel2.setText("Ingrese NIT: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, -1, 20));
        getContentPane().add(ctBuscarNIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 189, -1));

        btnBuscarNIT.setText("->");
        btnBuscarNIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarNITActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscarNIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, 90, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 732, 10));

        jLabel3.setText("NIT:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        lbNIT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lbNIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 138, 27));

        lbNombreCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lbNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 484, 27));

        jLabel4.setText("Nombre:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, -1));

        jLabel5.setText("Direccion");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        lbDireccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lbDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 689, 27));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 757, 10));

        jLabel6.setText("Busqueda:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));
        getContentPane().add(ctBuscarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 213, -1));

        cbOpcionDeBusqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Por Codigo", "Por Nombre" }));
        cbOpcionDeBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbOpcionDeBusquedaActionPerformed(evt);
            }
        });
        getContentPane().add(cbOpcionDeBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 121, -1));

        btnBuscarProducto.setText("Buscar");
        btnBuscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProductoActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 126, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setText("Codigo:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 15, -1, -1));

        jLabel8.setText("Nombre:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 48, -1, -1));

        jLabel9.setText("Tipo:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 75, -1, -1));

        jLabel10.setText("Farmaceutica");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 102, -1, -1));

        jLabel11.setText("Presentacion:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 17, -1, -1));

        jLabel12.setText("Composicion");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(412, 2, -1, -1));

        jLabel13.setText("Stock:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, -1, -1));

        jLabel14.setText("Precio: ");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, -1, -1));

        lbCodigoProducto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(lbCodigoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 15, 112, 20));

        lbNombreProducto.setText("  ");
        lbNombreProducto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(lbNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 46, 107, -1));

        lbTipoProducto.setText("  ");
        lbTipoProducto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(lbTipoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 73, 106, -1));

        lbFarmaceutica.setText("  ");
        lbFarmaceutica.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(lbFarmaceutica, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 100, 132, -1));

        lbPresentacion.setText("  ");
        lbPresentacion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(lbPresentacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 15, 75, -1));

        lbStock.setText("  ");
        lbStock.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(lbStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 70, -1));

        lbPrecio.setText(" ");
        lbPrecio.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(lbPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 63, -1));

        lbComposicion.setText("   ");
        lbComposicion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(lbComposicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 170, 61));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 428, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setText("Cantidad: ");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        spCantidadParaAgregar.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        jPanel3.add(spCantidadParaAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 60, -1));

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel3.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, 140, 100));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 780, 130));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 780, 10));

        jLabel16.setText("Factura:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        lbFactura.setText("  ");
        lbFactura.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lbFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 140, 20));

        tbProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbProductos.setEnabled(false);
        jScrollPane1.setViewportView(tbProductos);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 750, 190));

        jLabel18.setText("Fecha:");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 320, -1, -1));

        jLabel19.setText("Total Q. ");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 580, 60, -1));

        lbTotal.setText("     ");
        lbTotal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lbTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 580, 150, -1));

        jLabel21.setText("Cantidad Productos: ");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 580, -1, -1));

        lbCantidadProductos.setText("       ");
        lbCantidadProductos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lbCantidadProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 580, 90, -1));

        jLabel23.setText("Estatus");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 600, -1, -1));

        cbEstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pendiente", "Pagada" }));
        getContentPane().add(cbEstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 600, -1, -1));

        btnFacturar.setText("Generar Factura");
        btnFacturar.setEnabled(false);
        btnFacturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacturarActionPerformed(evt);
            }
        });
        getContentPane().add(btnFacturar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 600, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarNITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarNITActionPerformed
        String nit = ctBuscarNIT.getText().replaceAll(" ", "");
        if (!nit.equals("")) {
            System.out.println("lo que ingreso es: " + nit);
            clsQuerys objDetalleCliente = new clsQuerys();
            String[] detalleCliente = objDetalleCliente.fcnDetalleCliente(nit);
            if (detalleCliente[0] != null) {
                lbNIT.setText(detalleCliente[0]);
                lbNombreCliente.setText(detalleCliente[1]);
                lbDireccion.setText(detalleCliente[2]);
            } else {
                int option;
                option = JOptionPane.showConfirmDialog(null, "Este nit no existe, desea crearlo?", "no existe nit", ConfirmationCallback.YES_NO_OPTION);
                switch (option) {
                    case 0:
                        frmNit nuevoNit = new frmNit(nit);
                        this.setVisible(false);
                        nuevoNit.setVisible(true);
                        break;
                    case 1:
                        ctBuscarNIT.setText("");
                        break;
                    default:
                        break;
                }
            }
        }
    }//GEN-LAST:event_btnBuscarNITActionPerformed

    private void cbOpcionDeBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbOpcionDeBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbOpcionDeBusquedaActionPerformed

    private void btnBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProductoActionPerformed

        String valorParaBuscar = ctBuscarProducto.getText().replaceAll(" ", "");

        if (!valorParaBuscar.equals("")) {
            valorParaBuscar = ctBuscarProducto.getText();
            int tipoDeBusqueda = cbOpcionDeBusqueda.getSelectedIndex();
            clsQuerys objBusquedaProducto = new clsQuerys();
            String[] detallesDeProducto = null;
            switch (tipoDeBusqueda) {
                case 0 -> {
                    System.out.println("busqueda por codigo " + valorParaBuscar);
                    detallesDeProducto = objBusquedaProducto.fcnDetalleUnProducto(valorParaBuscar);
                }
                case 1 -> {
                    System.out.println("busqueda por nombre " + valorParaBuscar);
                    detallesDeProducto = objBusquedaProducto.fcnDetalleUnProductoPorNombre(valorParaBuscar);
                }
            }
            System.out.println("indice cero: " + detallesDeProducto[0]);
            if (detallesDeProducto[0] != null) {
                lbCodigoProducto.setText(detallesDeProducto[0]);
                lbNombreProducto.setText(detallesDeProducto[1]);
                lbTipoProducto.setText(detallesDeProducto[2]);
                lbFarmaceutica.setText(detallesDeProducto[3]);
                lbPresentacion.setText(detallesDeProducto[4]);
                lbStock.setText(detallesDeProducto[5]);
                lbPrecio.setText(detallesDeProducto[6]);
                lbComposicion.setText(detallesDeProducto[7]);
                System.gc();
            } else {
                JOptionPane.showMessageDialog(null, "No se encontro producto con esos datos", "AVISO", JOptionPane.OK_OPTION);

            }
        }
    }//GEN-LAST:event_btnBuscarProductoActionPerformed

    private void fncPintarTabla() {

        tbProductos.setModel(modeloConDatosDeTabla);
    }

    private void renovarTotales() {
        int cantidadTotalProductos = 0;
        double totalParaCobrar = 0;

        int totalFilas = modeloConDatosDeTabla.getRowCount();

        for (int i = 0; i < totalFilas; i++) {
            int datoCantidad = Integer.parseInt((String) modeloConDatosDeTabla.getValueAt(i, 3));
            double datoCobro = Double.parseDouble((String) modeloConDatosDeTabla.getValueAt(i, 5));
            cantidadTotalProductos += datoCantidad;
            totalParaCobrar += datoCobro;
        }
        lbCantidadProductos.setText(cantidadTotalProductos + "");
        lbTotal.setText(String.format("%.2f", totalParaCobrar));
    }


    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:

        if (!lbNIT.getText().equals("")) {
            if (!lbCodigoProducto.getText().equals("")) {
                int codigo = Integer.parseInt(lbCodigoProducto.getText());
                clsQuerys objProducto = new clsQuerys();
                String[] resultadosQuery = objProducto.fncDetalleProductoParaFactura(codigo);
                String[] datosParaInsertar = new String[7];
                int existencias = Integer.parseInt(resultadosQuery[1]);
                int agregar = (int) spCantidadParaAgregar.getValue();
                String nombre = resultadosQuery[0];
                double precio = Double.parseDouble(resultadosQuery[2]);

                if (existeCodigoEnModelo(codigo) < 0) {
                    //Si no existe el producto en la lista de la factura

                    //verifica si hay suficientes existencias para vender 
                    if (agregar <= existencias) {
                        String correlativo = Integer.toString(modeloConDatosDeTabla.getRowCount() + 1);
                        Double subtotal = precio * agregar;

                        //Correlativo
                        datosParaInsertar[0] = correlativo;
                        //codigo 
                        datosParaInsertar[1] = Integer.toString(codigo);
                        //nombre
                        datosParaInsertar[2] = nombre;
                        //Cantidad
                        datosParaInsertar[3] = agregar + "";
                        //precio
                        datosParaInsertar[4] = precio + "";
                        //subtotal
                        datosParaInsertar[5] = String.format("%.2f", subtotal);
                        //No. de Existencias
                        datosParaInsertar[6] = existencias + "";
                        modeloConDatosDeTabla.addRow(datosParaInsertar);

                    } else {
                        JOptionPane.showMessageDialog(null, "No hay suficientes existencias, unicamente hay " + existencias, "AVISO", JOptionPane.OK_OPTION);
                    }
                } else {
                    //Si el producto ya existe 
                    int indice = existeCodigoEnModelo(codigo);
                    System.out.println("indice " + indice);
                    String cantidadPreviaTexto = modeloConDatosDeTabla.getValueAt(indice, 3) + "";
                    int cantidadPrevia = Integer.parseInt(cantidadPreviaTexto);
                    System.out.println("cantidadprevia " + cantidadPrevia);
                    int cantidadNueva = agregar + cantidadPrevia;
                    System.out.println("cantidad nueva " + cantidadNueva);

                    if (cantidadNueva <= existencias) {
                        System.out.println("si se agrega ");
                        Double nuevoSubtotal = precio * cantidadNueva;
                        modeloConDatosDeTabla.setValueAt(cantidadNueva + "", indice, 3);
                        modeloConDatosDeTabla.setValueAt(String.format("%.2f", nuevoSubtotal), indice, 5);

                    } else {
                        JOptionPane.showMessageDialog(null, "No hay suficientes existencias, unicamente hay " + existencias, "AVISO", JOptionPane.OK_OPTION);
                    }

                }
                fncPintarTabla();
                renovarTotales();
                btnFacturar.setEnabled(true);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe tener un nit seleccionado", "AVISO", JOptionPane.OK_OPTION);
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnFacturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturarActionPerformed

        clsQuerys objInsert = new clsQuerys();
        String pNit = lbNIT.getText();
        String pCantidadProductos = lbCantidadProductos.getText();
        String pTotal = lbTotal.getText();
        String pEstatus = cbEstatus.getSelectedIndex()+ "";
        if (objInsert.fncInsertFactura(pNit, pCantidadProductos, pTotal, pEstatus)) {
            clsQuerys objFactura = new clsQuerys();
            String idFactura = objFactura.fncShowFacturaId();
            System.out.println("el string de id de factura es " + idFactura);

            int totalFilas = modeloConDatosDeTabla.getRowCount();

            for (int i = 0; i < totalFilas; i++) {
                int pFactura = Integer.parseInt(idFactura);
                int pCorrelativo = Integer.parseInt((String) modeloConDatosDeTabla.getValueAt(i, 0));
                int pCodigoProducto = Integer.parseInt((String) modeloConDatosDeTabla.getValueAt(i, 1));
                int pCantidad = Integer.parseInt((String) modeloConDatosDeTabla.getValueAt(i, 3));
                double pPrecio = Double.parseDouble((String) modeloConDatosDeTabla.getValueAt(i, 4));
                
                clsQuerys objDetallesFactura = new clsQuerys();
                objDetallesFactura.fncInsertDetalleFactura(pFactura, pCorrelativo, pCodigoProducto, pCantidad, pPrecio);
            }

        }


    }//GEN-LAST:event_btnFacturarActionPerformed

    //retorna -1 si aun no existe el codigo en el modelo, si ya existe devuelve su ubicacion
    private int existeCodigoEnModelo(int pCodigo) {
        int totalFilas = modeloConDatosDeTabla.getRowCount();
        //String valores = "";

        for (int i = 0; i < totalFilas; i++) {
            if (pCodigo == Integer.parseInt((String) modeloConDatosDeTabla.getValueAt(i, 1))) {
                return i;
            }
        }
        return -1;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmVenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscarNIT;
    private javax.swing.JButton btnBuscarProducto;
    private javax.swing.JButton btnFacturar;
    private javax.swing.JComboBox<String> cbEstatus;
    private javax.swing.JComboBox<String> cbOpcionDeBusqueda;
    private javax.swing.JTextField ctBuscarNIT;
    private javax.swing.JTextField ctBuscarProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lbCantidadProductos;
    private javax.swing.JLabel lbCodigoProducto;
    private javax.swing.JLabel lbComposicion;
    private javax.swing.JLabel lbDireccion;
    private javax.swing.JLabel lbFactura;
    private javax.swing.JLabel lbFarmaceutica;
    private javax.swing.JLabel lbNIT;
    private javax.swing.JLabel lbNombreCliente;
    private javax.swing.JLabel lbNombreProducto;
    private javax.swing.JLabel lbPrecio;
    private javax.swing.JLabel lbPresentacion;
    private javax.swing.JLabel lbStock;
    private javax.swing.JLabel lbTipoProducto;
    private javax.swing.JLabel lbTotal;
    private javax.swing.JSpinner spCantidadParaAgregar;
    private javax.swing.JTable tbProductos;
    // End of variables declaration//GEN-END:variables
}
